// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxarelrkfwszoudnlizx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54YXJlbHJrZndzem91ZG5saXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzA4OTMsImV4cCI6MjA2ODkwNjg5M30.jnQ2-eQRH5LnHVj6zZe4RFfLKrCCV0f0I5f-Q2Ps4zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});